# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "C:\Users\VOSTRO 3490\OneDrive\Desktop\TyC_Cpp"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "C:\Users\VOSTRO 3490\OneDrive\Desktop\TyC_Cpp"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool..."
	"C:\Program Files\CMake\bin\cpack.exe" --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool for source..."
	"C:\Program Files\CMake\bin\cpack.exe" --config ./CPackSourceConfig.cmake "C:/Users/VOSTRO 3490/OneDrive/Desktop/TyC_Cpp/CPackSourceConfig.cmake"
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\" \"dev\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	"C:\Program Files\CMake\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	"C:\Program Files\CMake\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "C:\Users\VOSTRO 3490\OneDrive\Desktop\TyC_Cpp\CMakeFiles" "C:\Users\VOSTRO 3490\OneDrive\Desktop\TyC_Cpp\\CMakeFiles\progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "C:\Users\VOSTRO 3490\OneDrive\Desktop\TyC_Cpp\CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named grammar

# Build rule for target.
grammar: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 grammar
.PHONY : grammar

# fast build rule for target.
grammar/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\grammar.dir\build.make CMakeFiles/grammar.dir/build
.PHONY : grammar/fast

#=============================================================================
# Target rules for targets named ast

# Build rule for target.
ast: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 ast
.PHONY : ast

# fast build rule for target.
ast/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ast.dir\build.make CMakeFiles/ast.dir/build
.PHONY : ast/fast

#=============================================================================
# Target rules for targets named checker

# Build rule for target.
checker: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 checker
.PHONY : checker

# fast build rule for target.
checker/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\checker.dir\build.make CMakeFiles/checker.dir/build
.PHONY : checker/fast

#=============================================================================
# Target rules for targets named codegen

# Build rule for target.
codegen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 codegen
.PHONY : codegen

# fast build rule for target.
codegen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\codegen.dir\build.make CMakeFiles/codegen.dir/build
.PHONY : codegen/fast

#=============================================================================
# Target rules for targets named testlib

# Build rule for target.
testlib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 testlib
.PHONY : testlib

# fast build rule for target.
testlib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testlib.dir\build.make CMakeFiles/testlib.dir/build
.PHONY : testlib/fast

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named antlr4_shared

# Build rule for target.
antlr4_shared: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 antlr4_shared
.PHONY : antlr4_shared

# fast build rule for target.
antlr4_shared/fast:
	$(MAKE) $(MAKESILENT) -f external\antlr4-cpp-runtime\runtime\CMakeFiles\antlr4_shared.dir\build.make external/antlr4-cpp-runtime/runtime/CMakeFiles/antlr4_shared.dir/build
.PHONY : antlr4_shared/fast

#=============================================================================
# Target rules for targets named antlr4_static

# Build rule for target.
antlr4_static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 antlr4_static
.PHONY : antlr4_static

# fast build rule for target.
antlr4_static/fast:
	$(MAKE) $(MAKESILENT) -f external\antlr4-cpp-runtime\runtime\CMakeFiles\antlr4_static.dir\build.make external/antlr4-cpp-runtime/runtime/CMakeFiles/antlr4_static.dir/build
.PHONY : antlr4_static/fast

#=============================================================================
# Target rules for targets named antlr4_tests

# Build rule for target.
antlr4_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 antlr4_tests
.PHONY : antlr4_tests

# fast build rule for target.
antlr4_tests/fast:
	$(MAKE) $(MAKESILENT) -f external\antlr4-cpp-runtime\runtime\CMakeFiles\antlr4_tests.dir\build.make external/antlr4-cpp-runtime/runtime/CMakeFiles/antlr4_tests.dir/build
.PHONY : antlr4_tests/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f _deps\googletest-build\googlemock\CMakeFiles\gmock.dir\build.make _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps\googletest-build\googlemock\CMakeFiles\gmock_main.dir\build.make _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f _deps\googletest-build\googletest\CMakeFiles\gtest.dir\build.make _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps\googletest-build\googletest\CMakeFiles\gtest_main.dir\build.make _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

AST/src/AST.obj: AST/src/AST.cpp.obj
.PHONY : AST/src/AST.obj

# target to build an object file
AST/src/AST.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ast.dir\build.make CMakeFiles/ast.dir/AST/src/AST.cpp.obj
.PHONY : AST/src/AST.cpp.obj

AST/src/AST.i: AST/src/AST.cpp.i
.PHONY : AST/src/AST.i

# target to preprocess a source file
AST/src/AST.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ast.dir\build.make CMakeFiles/ast.dir/AST/src/AST.cpp.i
.PHONY : AST/src/AST.cpp.i

AST/src/AST.s: AST/src/AST.cpp.s
.PHONY : AST/src/AST.s

# target to generate assembly for a file
AST/src/AST.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ast.dir\build.make CMakeFiles/ast.dir/AST/src/AST.cpp.s
.PHONY : AST/src/AST.cpp.s

AST/src/ASTGeneration.obj: AST/src/ASTGeneration.cpp.obj
.PHONY : AST/src/ASTGeneration.obj

# target to build an object file
AST/src/ASTGeneration.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ast.dir\build.make CMakeFiles/ast.dir/AST/src/ASTGeneration.cpp.obj
.PHONY : AST/src/ASTGeneration.cpp.obj

AST/src/ASTGeneration.i: AST/src/ASTGeneration.cpp.i
.PHONY : AST/src/ASTGeneration.i

# target to preprocess a source file
AST/src/ASTGeneration.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ast.dir\build.make CMakeFiles/ast.dir/AST/src/ASTGeneration.cpp.i
.PHONY : AST/src/ASTGeneration.cpp.i

AST/src/ASTGeneration.s: AST/src/ASTGeneration.cpp.s
.PHONY : AST/src/ASTGeneration.s

# target to generate assembly for a file
AST/src/ASTGeneration.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ast.dir\build.make CMakeFiles/ast.dir/AST/src/ASTGeneration.cpp.s
.PHONY : AST/src/ASTGeneration.cpp.s

CodeGenerator/src/CodeGenError.obj: CodeGenerator/src/CodeGenError.cpp.obj
.PHONY : CodeGenerator/src/CodeGenError.obj

# target to build an object file
CodeGenerator/src/CodeGenError.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\codegen.dir\build.make CMakeFiles/codegen.dir/CodeGenerator/src/CodeGenError.cpp.obj
.PHONY : CodeGenerator/src/CodeGenError.cpp.obj

CodeGenerator/src/CodeGenError.i: CodeGenerator/src/CodeGenError.cpp.i
.PHONY : CodeGenerator/src/CodeGenError.i

# target to preprocess a source file
CodeGenerator/src/CodeGenError.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\codegen.dir\build.make CMakeFiles/codegen.dir/CodeGenerator/src/CodeGenError.cpp.i
.PHONY : CodeGenerator/src/CodeGenError.cpp.i

CodeGenerator/src/CodeGenError.s: CodeGenerator/src/CodeGenError.cpp.s
.PHONY : CodeGenerator/src/CodeGenError.s

# target to generate assembly for a file
CodeGenerator/src/CodeGenError.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\codegen.dir\build.make CMakeFiles/codegen.dir/CodeGenerator/src/CodeGenError.cpp.s
.PHONY : CodeGenerator/src/CodeGenError.cpp.s

CodeGenerator/src/CodeGenerator.obj: CodeGenerator/src/CodeGenerator.cpp.obj
.PHONY : CodeGenerator/src/CodeGenerator.obj

# target to build an object file
CodeGenerator/src/CodeGenerator.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\codegen.dir\build.make CMakeFiles/codegen.dir/CodeGenerator/src/CodeGenerator.cpp.obj
.PHONY : CodeGenerator/src/CodeGenerator.cpp.obj

CodeGenerator/src/CodeGenerator.i: CodeGenerator/src/CodeGenerator.cpp.i
.PHONY : CodeGenerator/src/CodeGenerator.i

# target to preprocess a source file
CodeGenerator/src/CodeGenerator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\codegen.dir\build.make CMakeFiles/codegen.dir/CodeGenerator/src/CodeGenerator.cpp.i
.PHONY : CodeGenerator/src/CodeGenerator.cpp.i

CodeGenerator/src/CodeGenerator.s: CodeGenerator/src/CodeGenerator.cpp.s
.PHONY : CodeGenerator/src/CodeGenerator.s

# target to generate assembly for a file
CodeGenerator/src/CodeGenerator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\codegen.dir\build.make CMakeFiles/codegen.dir/CodeGenerator/src/CodeGenerator.cpp.s
.PHONY : CodeGenerator/src/CodeGenerator.cpp.s

CodeGenerator/src/Emitter.obj: CodeGenerator/src/Emitter.cpp.obj
.PHONY : CodeGenerator/src/Emitter.obj

# target to build an object file
CodeGenerator/src/Emitter.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\codegen.dir\build.make CMakeFiles/codegen.dir/CodeGenerator/src/Emitter.cpp.obj
.PHONY : CodeGenerator/src/Emitter.cpp.obj

CodeGenerator/src/Emitter.i: CodeGenerator/src/Emitter.cpp.i
.PHONY : CodeGenerator/src/Emitter.i

# target to preprocess a source file
CodeGenerator/src/Emitter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\codegen.dir\build.make CMakeFiles/codegen.dir/CodeGenerator/src/Emitter.cpp.i
.PHONY : CodeGenerator/src/Emitter.cpp.i

CodeGenerator/src/Emitter.s: CodeGenerator/src/Emitter.cpp.s
.PHONY : CodeGenerator/src/Emitter.s

# target to generate assembly for a file
CodeGenerator/src/Emitter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\codegen.dir\build.make CMakeFiles/codegen.dir/CodeGenerator/src/Emitter.cpp.s
.PHONY : CodeGenerator/src/Emitter.cpp.s

CodeGenerator/src/Frame.obj: CodeGenerator/src/Frame.cpp.obj
.PHONY : CodeGenerator/src/Frame.obj

# target to build an object file
CodeGenerator/src/Frame.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\codegen.dir\build.make CMakeFiles/codegen.dir/CodeGenerator/src/Frame.cpp.obj
.PHONY : CodeGenerator/src/Frame.cpp.obj

CodeGenerator/src/Frame.i: CodeGenerator/src/Frame.cpp.i
.PHONY : CodeGenerator/src/Frame.i

# target to preprocess a source file
CodeGenerator/src/Frame.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\codegen.dir\build.make CMakeFiles/codegen.dir/CodeGenerator/src/Frame.cpp.i
.PHONY : CodeGenerator/src/Frame.cpp.i

CodeGenerator/src/Frame.s: CodeGenerator/src/Frame.cpp.s
.PHONY : CodeGenerator/src/Frame.s

# target to generate assembly for a file
CodeGenerator/src/Frame.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\codegen.dir\build.make CMakeFiles/codegen.dir/CodeGenerator/src/Frame.cpp.s
.PHONY : CodeGenerator/src/Frame.cpp.s

CodeGenerator/src/MachineCode.obj: CodeGenerator/src/MachineCode.cpp.obj
.PHONY : CodeGenerator/src/MachineCode.obj

# target to build an object file
CodeGenerator/src/MachineCode.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\codegen.dir\build.make CMakeFiles/codegen.dir/CodeGenerator/src/MachineCode.cpp.obj
.PHONY : CodeGenerator/src/MachineCode.cpp.obj

CodeGenerator/src/MachineCode.i: CodeGenerator/src/MachineCode.cpp.i
.PHONY : CodeGenerator/src/MachineCode.i

# target to preprocess a source file
CodeGenerator/src/MachineCode.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\codegen.dir\build.make CMakeFiles/codegen.dir/CodeGenerator/src/MachineCode.cpp.i
.PHONY : CodeGenerator/src/MachineCode.cpp.i

CodeGenerator/src/MachineCode.s: CodeGenerator/src/MachineCode.cpp.s
.PHONY : CodeGenerator/src/MachineCode.s

# target to generate assembly for a file
CodeGenerator/src/MachineCode.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\codegen.dir\build.make CMakeFiles/codegen.dir/CodeGenerator/src/MachineCode.cpp.s
.PHONY : CodeGenerator/src/MachineCode.cpp.s

Grammar/src/lexererr.obj: Grammar/src/lexererr.cpp.obj
.PHONY : Grammar/src/lexererr.obj

# target to build an object file
Grammar/src/lexererr.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\grammar.dir\build.make CMakeFiles/grammar.dir/Grammar/src/lexererr.cpp.obj
.PHONY : Grammar/src/lexererr.cpp.obj

Grammar/src/lexererr.i: Grammar/src/lexererr.cpp.i
.PHONY : Grammar/src/lexererr.i

# target to preprocess a source file
Grammar/src/lexererr.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\grammar.dir\build.make CMakeFiles/grammar.dir/Grammar/src/lexererr.cpp.i
.PHONY : Grammar/src/lexererr.cpp.i

Grammar/src/lexererr.s: Grammar/src/lexererr.cpp.s
.PHONY : Grammar/src/lexererr.s

# target to generate assembly for a file
Grammar/src/lexererr.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\grammar.dir\build.make CMakeFiles/grammar.dir/Grammar/src/lexererr.cpp.s
.PHONY : Grammar/src/lexererr.cpp.s

Grammar/target/TyCBaseVisitor.obj: Grammar/target/TyCBaseVisitor.cpp.obj
.PHONY : Grammar/target/TyCBaseVisitor.obj

# target to build an object file
Grammar/target/TyCBaseVisitor.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\grammar.dir\build.make CMakeFiles/grammar.dir/Grammar/target/TyCBaseVisitor.cpp.obj
.PHONY : Grammar/target/TyCBaseVisitor.cpp.obj

Grammar/target/TyCBaseVisitor.i: Grammar/target/TyCBaseVisitor.cpp.i
.PHONY : Grammar/target/TyCBaseVisitor.i

# target to preprocess a source file
Grammar/target/TyCBaseVisitor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\grammar.dir\build.make CMakeFiles/grammar.dir/Grammar/target/TyCBaseVisitor.cpp.i
.PHONY : Grammar/target/TyCBaseVisitor.cpp.i

Grammar/target/TyCBaseVisitor.s: Grammar/target/TyCBaseVisitor.cpp.s
.PHONY : Grammar/target/TyCBaseVisitor.s

# target to generate assembly for a file
Grammar/target/TyCBaseVisitor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\grammar.dir\build.make CMakeFiles/grammar.dir/Grammar/target/TyCBaseVisitor.cpp.s
.PHONY : Grammar/target/TyCBaseVisitor.cpp.s

Grammar/target/TyCLexer.obj: Grammar/target/TyCLexer.cpp.obj
.PHONY : Grammar/target/TyCLexer.obj

# target to build an object file
Grammar/target/TyCLexer.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\grammar.dir\build.make CMakeFiles/grammar.dir/Grammar/target/TyCLexer.cpp.obj
.PHONY : Grammar/target/TyCLexer.cpp.obj

Grammar/target/TyCLexer.i: Grammar/target/TyCLexer.cpp.i
.PHONY : Grammar/target/TyCLexer.i

# target to preprocess a source file
Grammar/target/TyCLexer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\grammar.dir\build.make CMakeFiles/grammar.dir/Grammar/target/TyCLexer.cpp.i
.PHONY : Grammar/target/TyCLexer.cpp.i

Grammar/target/TyCLexer.s: Grammar/target/TyCLexer.cpp.s
.PHONY : Grammar/target/TyCLexer.s

# target to generate assembly for a file
Grammar/target/TyCLexer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\grammar.dir\build.make CMakeFiles/grammar.dir/Grammar/target/TyCLexer.cpp.s
.PHONY : Grammar/target/TyCLexer.cpp.s

Grammar/target/TyCParser.obj: Grammar/target/TyCParser.cpp.obj
.PHONY : Grammar/target/TyCParser.obj

# target to build an object file
Grammar/target/TyCParser.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\grammar.dir\build.make CMakeFiles/grammar.dir/Grammar/target/TyCParser.cpp.obj
.PHONY : Grammar/target/TyCParser.cpp.obj

Grammar/target/TyCParser.i: Grammar/target/TyCParser.cpp.i
.PHONY : Grammar/target/TyCParser.i

# target to preprocess a source file
Grammar/target/TyCParser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\grammar.dir\build.make CMakeFiles/grammar.dir/Grammar/target/TyCParser.cpp.i
.PHONY : Grammar/target/TyCParser.cpp.i

Grammar/target/TyCParser.s: Grammar/target/TyCParser.cpp.s
.PHONY : Grammar/target/TyCParser.s

# target to generate assembly for a file
Grammar/target/TyCParser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\grammar.dir\build.make CMakeFiles/grammar.dir/Grammar/target/TyCParser.cpp.s
.PHONY : Grammar/target/TyCParser.cpp.s

Grammar/target/TyCVisitor.obj: Grammar/target/TyCVisitor.cpp.obj
.PHONY : Grammar/target/TyCVisitor.obj

# target to build an object file
Grammar/target/TyCVisitor.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\grammar.dir\build.make CMakeFiles/grammar.dir/Grammar/target/TyCVisitor.cpp.obj
.PHONY : Grammar/target/TyCVisitor.cpp.obj

Grammar/target/TyCVisitor.i: Grammar/target/TyCVisitor.cpp.i
.PHONY : Grammar/target/TyCVisitor.i

# target to preprocess a source file
Grammar/target/TyCVisitor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\grammar.dir\build.make CMakeFiles/grammar.dir/Grammar/target/TyCVisitor.cpp.i
.PHONY : Grammar/target/TyCVisitor.cpp.i

Grammar/target/TyCVisitor.s: Grammar/target/TyCVisitor.cpp.s
.PHONY : Grammar/target/TyCVisitor.s

# target to generate assembly for a file
Grammar/target/TyCVisitor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\grammar.dir\build.make CMakeFiles/grammar.dir/Grammar/target/TyCVisitor.cpp.s
.PHONY : Grammar/target/TyCVisitor.cpp.s

StaticChecker/src/StaticChecker.obj: StaticChecker/src/StaticChecker.cpp.obj
.PHONY : StaticChecker/src/StaticChecker.obj

# target to build an object file
StaticChecker/src/StaticChecker.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\checker.dir\build.make CMakeFiles/checker.dir/StaticChecker/src/StaticChecker.cpp.obj
.PHONY : StaticChecker/src/StaticChecker.cpp.obj

StaticChecker/src/StaticChecker.i: StaticChecker/src/StaticChecker.cpp.i
.PHONY : StaticChecker/src/StaticChecker.i

# target to preprocess a source file
StaticChecker/src/StaticChecker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\checker.dir\build.make CMakeFiles/checker.dir/StaticChecker/src/StaticChecker.cpp.i
.PHONY : StaticChecker/src/StaticChecker.cpp.i

StaticChecker/src/StaticChecker.s: StaticChecker/src/StaticChecker.cpp.s
.PHONY : StaticChecker/src/StaticChecker.s

# target to generate assembly for a file
StaticChecker/src/StaticChecker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\checker.dir\build.make CMakeFiles/checker.dir/StaticChecker/src/StaticChecker.cpp.s
.PHONY : StaticChecker/src/StaticChecker.cpp.s

StaticChecker/src/StaticError.obj: StaticChecker/src/StaticError.cpp.obj
.PHONY : StaticChecker/src/StaticError.obj

# target to build an object file
StaticChecker/src/StaticError.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\checker.dir\build.make CMakeFiles/checker.dir/StaticChecker/src/StaticError.cpp.obj
.PHONY : StaticChecker/src/StaticError.cpp.obj

StaticChecker/src/StaticError.i: StaticChecker/src/StaticError.cpp.i
.PHONY : StaticChecker/src/StaticError.i

# target to preprocess a source file
StaticChecker/src/StaticError.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\checker.dir\build.make CMakeFiles/checker.dir/StaticChecker/src/StaticError.cpp.i
.PHONY : StaticChecker/src/StaticError.cpp.i

StaticChecker/src/StaticError.s: StaticChecker/src/StaticError.cpp.s
.PHONY : StaticChecker/src/StaticError.s

# target to generate assembly for a file
StaticChecker/src/StaticError.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\checker.dir\build.make CMakeFiles/checker.dir/StaticChecker/src/StaticError.cpp.s
.PHONY : StaticChecker/src/StaticError.cpp.s

main.obj: main.cpp.obj
.PHONY : main.obj

# target to build an object file
main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/main.cpp.obj
.PHONY : main.cpp.obj

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

test/src/ASTGenSuite.obj: test/src/ASTGenSuite.cpp.obj
.PHONY : test/src/ASTGenSuite.obj

# target to build an object file
test/src/ASTGenSuite.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testlib.dir\build.make CMakeFiles/testlib.dir/test/src/ASTGenSuite.cpp.obj
.PHONY : test/src/ASTGenSuite.cpp.obj

test/src/ASTGenSuite.i: test/src/ASTGenSuite.cpp.i
.PHONY : test/src/ASTGenSuite.i

# target to preprocess a source file
test/src/ASTGenSuite.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testlib.dir\build.make CMakeFiles/testlib.dir/test/src/ASTGenSuite.cpp.i
.PHONY : test/src/ASTGenSuite.cpp.i

test/src/ASTGenSuite.s: test/src/ASTGenSuite.cpp.s
.PHONY : test/src/ASTGenSuite.s

# target to generate assembly for a file
test/src/ASTGenSuite.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testlib.dir\build.make CMakeFiles/testlib.dir/test/src/ASTGenSuite.cpp.s
.PHONY : test/src/ASTGenSuite.cpp.s

test/src/CheckerSuite.obj: test/src/CheckerSuite.cpp.obj
.PHONY : test/src/CheckerSuite.obj

# target to build an object file
test/src/CheckerSuite.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testlib.dir\build.make CMakeFiles/testlib.dir/test/src/CheckerSuite.cpp.obj
.PHONY : test/src/CheckerSuite.cpp.obj

test/src/CheckerSuite.i: test/src/CheckerSuite.cpp.i
.PHONY : test/src/CheckerSuite.i

# target to preprocess a source file
test/src/CheckerSuite.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testlib.dir\build.make CMakeFiles/testlib.dir/test/src/CheckerSuite.cpp.i
.PHONY : test/src/CheckerSuite.cpp.i

test/src/CheckerSuite.s: test/src/CheckerSuite.cpp.s
.PHONY : test/src/CheckerSuite.s

# target to generate assembly for a file
test/src/CheckerSuite.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testlib.dir\build.make CMakeFiles/testlib.dir/test/src/CheckerSuite.cpp.s
.PHONY : test/src/CheckerSuite.cpp.s

test/src/CodeGenSuite.obj: test/src/CodeGenSuite.cpp.obj
.PHONY : test/src/CodeGenSuite.obj

# target to build an object file
test/src/CodeGenSuite.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testlib.dir\build.make CMakeFiles/testlib.dir/test/src/CodeGenSuite.cpp.obj
.PHONY : test/src/CodeGenSuite.cpp.obj

test/src/CodeGenSuite.i: test/src/CodeGenSuite.cpp.i
.PHONY : test/src/CodeGenSuite.i

# target to preprocess a source file
test/src/CodeGenSuite.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testlib.dir\build.make CMakeFiles/testlib.dir/test/src/CodeGenSuite.cpp.i
.PHONY : test/src/CodeGenSuite.cpp.i

test/src/CodeGenSuite.s: test/src/CodeGenSuite.cpp.s
.PHONY : test/src/CodeGenSuite.s

# target to generate assembly for a file
test/src/CodeGenSuite.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testlib.dir\build.make CMakeFiles/testlib.dir/test/src/CodeGenSuite.cpp.s
.PHONY : test/src/CodeGenSuite.cpp.s

test/src/LexerSuite.obj: test/src/LexerSuite.cpp.obj
.PHONY : test/src/LexerSuite.obj

# target to build an object file
test/src/LexerSuite.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testlib.dir\build.make CMakeFiles/testlib.dir/test/src/LexerSuite.cpp.obj
.PHONY : test/src/LexerSuite.cpp.obj

test/src/LexerSuite.i: test/src/LexerSuite.cpp.i
.PHONY : test/src/LexerSuite.i

# target to preprocess a source file
test/src/LexerSuite.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testlib.dir\build.make CMakeFiles/testlib.dir/test/src/LexerSuite.cpp.i
.PHONY : test/src/LexerSuite.cpp.i

test/src/LexerSuite.s: test/src/LexerSuite.cpp.s
.PHONY : test/src/LexerSuite.s

# target to generate assembly for a file
test/src/LexerSuite.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testlib.dir\build.make CMakeFiles/testlib.dir/test/src/LexerSuite.cpp.s
.PHONY : test/src/LexerSuite.cpp.s

test/src/ParserSuite.obj: test/src/ParserSuite.cpp.obj
.PHONY : test/src/ParserSuite.obj

# target to build an object file
test/src/ParserSuite.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testlib.dir\build.make CMakeFiles/testlib.dir/test/src/ParserSuite.cpp.obj
.PHONY : test/src/ParserSuite.cpp.obj

test/src/ParserSuite.i: test/src/ParserSuite.cpp.i
.PHONY : test/src/ParserSuite.i

# target to preprocess a source file
test/src/ParserSuite.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testlib.dir\build.make CMakeFiles/testlib.dir/test/src/ParserSuite.cpp.i
.PHONY : test/src/ParserSuite.cpp.i

test/src/ParserSuite.s: test/src/ParserSuite.cpp.s
.PHONY : test/src/ParserSuite.s

# target to generate assembly for a file
test/src/ParserSuite.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testlib.dir\build.make CMakeFiles/testlib.dir/test/src/ParserSuite.cpp.s
.PHONY : test/src/ParserSuite.cpp.s

test/src/TestUtils.obj: test/src/TestUtils.cpp.obj
.PHONY : test/src/TestUtils.obj

# target to build an object file
test/src/TestUtils.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testlib.dir\build.make CMakeFiles/testlib.dir/test/src/TestUtils.cpp.obj
.PHONY : test/src/TestUtils.cpp.obj

test/src/TestUtils.i: test/src/TestUtils.cpp.i
.PHONY : test/src/TestUtils.i

# target to preprocess a source file
test/src/TestUtils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testlib.dir\build.make CMakeFiles/testlib.dir/test/src/TestUtils.cpp.i
.PHONY : test/src/TestUtils.cpp.i

test/src/TestUtils.s: test/src/TestUtils.cpp.s
.PHONY : test/src/TestUtils.s

# target to generate assembly for a file
test/src/TestUtils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testlib.dir\build.make CMakeFiles/testlib.dir/test/src/TestUtils.cpp.s
.PHONY : test/src/TestUtils.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... install
	@echo ... install/local
	@echo ... install/strip
	@echo ... list_install_components
	@echo ... package
	@echo ... package_source
	@echo ... rebuild_cache
	@echo ... antlr4_shared
	@echo ... antlr4_static
	@echo ... antlr4_tests
	@echo ... ast
	@echo ... checker
	@echo ... codegen
	@echo ... gmock
	@echo ... gmock_main
	@echo ... grammar
	@echo ... gtest
	@echo ... gtest_main
	@echo ... main
	@echo ... testlib
	@echo ... AST/src/AST.obj
	@echo ... AST/src/AST.i
	@echo ... AST/src/AST.s
	@echo ... AST/src/ASTGeneration.obj
	@echo ... AST/src/ASTGeneration.i
	@echo ... AST/src/ASTGeneration.s
	@echo ... CodeGenerator/src/CodeGenError.obj
	@echo ... CodeGenerator/src/CodeGenError.i
	@echo ... CodeGenerator/src/CodeGenError.s
	@echo ... CodeGenerator/src/CodeGenerator.obj
	@echo ... CodeGenerator/src/CodeGenerator.i
	@echo ... CodeGenerator/src/CodeGenerator.s
	@echo ... CodeGenerator/src/Emitter.obj
	@echo ... CodeGenerator/src/Emitter.i
	@echo ... CodeGenerator/src/Emitter.s
	@echo ... CodeGenerator/src/Frame.obj
	@echo ... CodeGenerator/src/Frame.i
	@echo ... CodeGenerator/src/Frame.s
	@echo ... CodeGenerator/src/MachineCode.obj
	@echo ... CodeGenerator/src/MachineCode.i
	@echo ... CodeGenerator/src/MachineCode.s
	@echo ... Grammar/src/lexererr.obj
	@echo ... Grammar/src/lexererr.i
	@echo ... Grammar/src/lexererr.s
	@echo ... Grammar/target/TyCBaseVisitor.obj
	@echo ... Grammar/target/TyCBaseVisitor.i
	@echo ... Grammar/target/TyCBaseVisitor.s
	@echo ... Grammar/target/TyCLexer.obj
	@echo ... Grammar/target/TyCLexer.i
	@echo ... Grammar/target/TyCLexer.s
	@echo ... Grammar/target/TyCParser.obj
	@echo ... Grammar/target/TyCParser.i
	@echo ... Grammar/target/TyCParser.s
	@echo ... Grammar/target/TyCVisitor.obj
	@echo ... Grammar/target/TyCVisitor.i
	@echo ... Grammar/target/TyCVisitor.s
	@echo ... StaticChecker/src/StaticChecker.obj
	@echo ... StaticChecker/src/StaticChecker.i
	@echo ... StaticChecker/src/StaticChecker.s
	@echo ... StaticChecker/src/StaticError.obj
	@echo ... StaticChecker/src/StaticError.i
	@echo ... StaticChecker/src/StaticError.s
	@echo ... main.obj
	@echo ... main.i
	@echo ... main.s
	@echo ... test/src/ASTGenSuite.obj
	@echo ... test/src/ASTGenSuite.i
	@echo ... test/src/ASTGenSuite.s
	@echo ... test/src/CheckerSuite.obj
	@echo ... test/src/CheckerSuite.i
	@echo ... test/src/CheckerSuite.s
	@echo ... test/src/CodeGenSuite.obj
	@echo ... test/src/CodeGenSuite.i
	@echo ... test/src/CodeGenSuite.s
	@echo ... test/src/LexerSuite.obj
	@echo ... test/src/LexerSuite.i
	@echo ... test/src/LexerSuite.s
	@echo ... test/src/ParserSuite.obj
	@echo ... test/src/ParserSuite.i
	@echo ... test/src/ParserSuite.s
	@echo ... test/src/TestUtils.obj
	@echo ... test/src/TestUtils.i
	@echo ... test/src/TestUtils.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

